#!/bin/bash

if [ -f /home/zenk/.crontab.bak ]
then
	old="$(md5sum /home/zenk/.crontab.bak | cut -d ' ' -f 1)"
	current="$(md5sum /etc/crontab | cut -d ' ' -f 1)"

	if [ "$old" == "$current" ]
	then
		exit 0
	else
		echo "/etc/crontab has been modified !!!" | mail root
		cat /etc/crontab > /home/zenk/.crontab.bak
	fi
else
	echo "no old file ... let's create one"
	cat /etc/crontab > /home/zenk/.crontab.bak
fi